Task 2

In [16]:
# Task 2 (i) Reading and Writing from a file
# to read from file1
file1=open("File1.txt","r")
data=file1.read()
# to write in file2

file2=open("File2.txt","w")
file2.write(data)
# closing the file objects
file1.close()
file2.close()


# Task 2 (ii)  To write a dictionary in a file 
dict={
    "name":"Sanjeet Raj",
    "roll":2306009,
    "language":"python"
}

# using pickle 
import pickle
file3=open("File3.txt","wb")

pickle.dump(dict,file3)
file3.close()

# normally
file3=open("File3.txt","w")
file3.write("{")
for i in dict:
    text=str(i)+":"+str(dict[i])+","
    file3.write(text)
file3.write("}")
file3.close()


# Task 2 (iii) Finding the size of a file
import os
f=os.path.getsize("./File1.txt")
print("Size of the given file:",f)


# Task 2 (iv) Most repeated word

file1=open("File1.txt","r")
str1=""
data=file1.read()
file1.close()
for i in range(len(data)):
    if(not(data[i].isalnum())):
        str1=str1+" "
    else:
        str1+=data[i]
array=str1.split(None)

wordDict={}
for i in array :
    if i in wordDict:
        wordDict[i]+=1
    else:
        wordDict[i]=1
max=0
lWord=""
for i in wordDict:
    if wordDict[i]>max:
        max=wordDict[i]
        lWord=i

print("Most repeated word in file:",lWord,"\t\t freq:",max,"times")


# Task 2 (v) Read Specific Lines from a file
file1=open("File1.txt","r")
data=file1.readlines()
file1.close()
index=int(input("Enter the line number to read:"))
print(f"line at line number {index} is ")
print(data[index-1])

Size of the given file: 128
Most repeated word in file: is 		 freq: 2 times
line at line number 1 is
This is the first file .

Task 3

In [17]:
import numpy as np

In [18]:
# 1.Create an empty and full array
# Empty array
nums1=np.empty(9)
nums1

array([5.34050071e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000])

In [19]:
# Full array
nums2=np.full((1,6),23)
nums2

array([[23, 23, 23, 23, 23, 23]])

In [20]:
# 2.Array with all zeroes
numsZeroes=np.zeros((3,3))
numsZeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# 4.Replace numpy array elements that does not follow a given condition

nums5=np.arange(11,38,3).reshape(3,3)
# before replacement
nums5

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [22]:
# Condition :elements divisible by 2
cond=nums5%2==0
# Replacing all the elements which are not divisible by two with nan
nums5=np.where(cond,nums5,np.nan)
nums5

array([[nan, 14., nan],
       [20., nan, 26.],
       [nan, 32., nan]])

In [23]:
# Condition :elements divisible by 2
cond=nums5%2==0
# Replacing all the elements which are not divisible by two with nan
nums5=np.where(cond,nums5,np.nan)
nums5

array([[nan, 14., nan],
       [20., nan, 26.],
       [nan, 32., nan]])

In [24]:
# 3.Array with all ones
numsOnes=np.ones((3,3),dtype=int)
numsOnes

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Task 4

In [25]:
#Task4
import pandas as pd

In [26]:
df=pd.read_csv("./Student Degree College Data.csv")

In [27]:
df.head()

,form_no,name,category,minority,gender,hs_total,hs_pass_year,first_choice_sub,first_choice_marks,second_choice_sub,second_choice_marks,first_choice_stream,second_choice_stream
0,1801371,Susmita Bhowmik,UR,NO,F,381,2018,Mathematics,80,Mathematics,80,Physical Science,Physical Science
1,1803096,Ankur Das,SC,NO,M,262,2018,Education,61,Bengali,58,Arts,Arts
2,1801287,Rashmita Tanti,UR,NO,M,278,2018,Human Physiology,74,Botany,74,Bio Science,Bio Science
3,1803173,Sanjib Ghosh,UR,NO,M,194,2018,NaN,0,NaN,0,Arts,Arts
4,1801077,Swarupa Pal,UR,NO,F,320,2015,NaN,0,NaN,0,Bio Science,Bio Science

In [28]:
# 1Split a column in pandas dataframe and get a part of it
fname=df["name"].str.split(" ").str[0].to_list()
fname

['Susmita',
 'Ankur',
 'Rashmita',
 'Sanjib',
 'Swarupa',
 'Abhijit',
 'Susmita',
 'Snehabrata',
 'Bijan',
 'Supratip',
 'Tania',
 'Paramita',
 'Abhik',
 'Naina',
 'Paulami',
 'Anirban',
 'Sudrip',
 'Parmita',
 'Biswambar',
 'Shayal',
 'Koshik',
 'Sauratabha',
 'Lalanjoy',
 'Silvana',
 'Moumita',
 'Mousumi',
 'Saini',
 'Rupanjali',
 'Ankita',
 'Balai',
 'Prasanta',
 'Dwipjyoti',
 'Akash',
 'Snigdha',
 'Pritam',
 'Deep',
 'Sumit',
 'Sneha',
 'Rohini',
 'Tanik',
 'Oishi',
 'Sayan',
 'Sushrita',
 'Rahul',
 'Sarita',
 'Sagarika',
 'Nabarun',
 'Supratim',
 'Puja',
 'Arpita',
 'Mijanur',
 'Sarbani',
 'Kishan',
 'Amit',
 'Sipan',
 'Habibur',
 'Gagan',
 'Surmista',
 'Saoli',
 'Swarup',
 'Soumyadip',
 'Krishan',
 'Baishali',
 'Debajit',
 'Shuhardha',
 'Rikta',
 'Saptadipa',
 'Rimisoma',
 'Sujan',
 'Manish',
 'Bidisha',
 'Ramprasad',
 'Santanu',
 'Poulami',
 'Krishna',
 'Arpita',
 'Trisha',
 'Monalisa',
 'Anirban',
 'Tanusri',
 'Soma',
 'Twinkel',
 'Dibyendu',
 'Diptanu',
 'Arpita',
 'Tapas',
 'Akash',
 'Jhulan',
 'Chandan',
 'Swasti',
 'Gourab',
 'Souvik',
 'Priyadeep',
 'Payal',
 'Tania',
 'Mithun',
 'Bishnu',
 'Eachin',
 'Tapas',
 'Susmita',
 'Dipantar',
 'Bishak',
 'Dipjoy',
 'Rupak',
 'Sagar',
 'Sweta',
 'Nabanita',
 'Munni',
 'Subhajit',
 'Ashit',
 'Arabinda',
 'Akash',
 'Partha',
 'Tarak',
 'Azizul',
 'Abhinas',
 'Manti',
 'Md',
 'Soniya',
 'Sourav',
 'Prasenjit',
 'Rana',
 'Debajyoti',
 'Sagar',
 'Anannya',
 'Sagarika',
 'Santu',
 'Subhajit',
 'Subhankar',
 'Swarop',
 'Mampi',
 'Mousumi',
 'Nandita',
 'Riya',
 'Juma',
 'Ruhit',
 'Sharmistha',
 'Krishna',
 'Sudipa',
 'Ankit',
 'Rahul',
 'Moumita',
 'Ranit',
 'Kowshik',
 'Abel',
 'Anamika',
 'Rupankar',
 'Rashmi',
 'Bishal',
 'Ajoy',
 'Riya',
 'Sankar',
 'Debarpita',
 'Kanzam',
 'Rohita',
 'Babita',
 'Tirtha',
 'Arpita',
 'Suvam',
 'Gitashree',
 'Papri',
 'Shilpasri',
 'Hambai',
 'Debraj',
 'Rajeswari',
 'Pritam',
 'Pinaki',
 'Sudipta',
 'Juel',
 'Shilpi',
 'Joyjit',
 'Anamika',
 'Ruma',
 'Rahul',
 'Tanima',
 'Debabrata',
 'Ila',
 'Saptarshi',
 'Priyanka',
 'Rupashree',
 'Priyanka',
 'Tusar',
 'Niha',
 'Kamala',
 'Shantanu',
 'Hariprasad',
 'Pranab',
 'Purnanjali',
 'Priya',
 'Trishika',
 'Sagar',
 'Antara',
 'Krishan',
 'Roma',
 'Tania',
 'Pankaj',
 'Manisha',
 'Sumit',
 'Chinmoy',
 'Sanjita',
 'Washim',
 'Rina',
 'Deep',
 'Bithika',
 'Debarun',
 'Supriya',
 'Rituparna',
 'Susmita',
 'Priti',
 'Ranatunga',
 'Tania',
 'Dibang',
 'Rahul',
 'Jaya',
 'Pritam',
 'Karnajit',
 'Jhuma',
 'Jui',
 'Mousumi',
 'Bibak',
 'Papiya',
 'Amit',
 'Arunabha',
 'Sumita',
 'Subhajit',
 'Papiya',
 'Sanu',
 'Biswajit',
 'Supriti',
 'Bishal',
 'Tapash',
 'Subhadeep',
 'Suchi',
 'Pritam',
 'Nandita',
 'Suraj',
 'Arohi',
 'Pran',
 'Payel',
 'Pranoy',
 'Ajoy',
 'Santanu',
 'Subham',
 'Pantwi',
 'Sourav',
 'Biki',
 'Sourabh',
 'Dipika',
 'Bishal',
 'Srestha',
 'Papai',
 'Disha',
 'Shraddha',
 'Ram',
 'Diptanu',
 'Debarati',
 'Mehenaz',
 'Epsita',
 'Siddhartha',
 'Smita',
 'Saurav',
 'Panna',
 'Puja',
 'Sukanta',
 'Sayantan',
 'Ajoy',
 'Nitika',
 'Diptanu',
 'Snigdha',
 'Puja',
 'Achinta',
 'Ankita',
 'Dalia',
 'Akhi',
 'Sukanta',
 'Jhinuk',
 'Tania',
 'Isha',
 'Saslang',
 'Pulakesh',
 'Jasim',
 'Suniket',
 'Tanmoy',
 'Subhrajit',
 'Lalrotlinga',
 'Papai',
 'Sneha',
 'Ram',
 'Suraj',
 'Priyanka',
 'Suraj',
 'Ishita',
 'Jahnnabi',
 'Pintu',
 'Dilen',
 'Ankita',
 'Bijoy',
 'Debjani',
 'Abinash',
 'Arati',
 'Rupam',
 'Jyotibikash',
 'Akash',
 'Bishal',
 'Akash',
 'Mampi',
 'Debasri',
 'Rakesh',
 'Sankar',
 'Subhajyoti',
 'Tusharika',
 'Debjyoti',
 'Shibu',
 'Dipankar',
 'Subhajit',
 'Deepa',
 'Dipak',
 'Arkajit',
 'Susmita',
 'Priyanka',
 'Prasenjit',
 'Udichi',
 'Ankita',
 'Manku',
 'Lokesh',
 'Srabani',
 'Arnab',
 'Remon',
 'Manali',
 'Namita',
 'Bhumika',
 'Subham',
 'Prativa',
 'Sonali',
 'Maharun',
 'Dipankar',
 'Tanmoy',
 'Digbijoy',
 'Subhrajit',
 'Abhijit',
 'Apangshu',
 'Md',
 'Akash',
 'Madhabi',
 'Sumit',
 'Bishal',
 'Mousam',
 'Dipa',
 'Dipam',
 'Rahul',
 'Tina',
 'Sangita',
 'Jayashree',
 'Sanchita',
 'Priyanka',
 'Sagar',
 'Mona',
 'Keya',
 'Baisali',
 'Bishu',
 'Prasanna',
 'Bijita',
 'Sourav',
 'Tanisha',
 'Utsarga',
 'Kalika',
 'Subhrajit',
 'Gariyashi',
 'Soma',
 'Dharmendu',
 'Souralina',
 'Satabdi',
 'Priya',
 'Priyanka',
 'Sonia',
 'Kaushik',
 'Susmita',
 'Mayuri',
 'Swarup',
 'Manodipa',
 'Laxmi',
 'Brani',
 'Mandira',
 'Akash',
 'Karnajit',
 'Arnab',
 'Rupak',
 'Rashed',
 'Abhijit',
 'Manali',
 'Arindam',
 'Rinki',
 'Manisha',
 'Arajit',
 'Sourav',
 'Ashmita',
 'Abinash',
 'Poushali',
 'Bimalendu',
 'Debabrata',
 'Sanchita',
 'Jesmin',
 'Sayan',
 'Alisha',
 'Sutapa',
 'Arpita',
 'Puja',
 'Swastika',
 'Sahel',
 'Beauty',
 'Manushree',
 'Giniya',
 'Debasmita',
 'Bindhiya',
 'Arijit',
 'Prasenjit',
 'Pritam',
 'Sanu',
 'Pulak',
 'Suraj',
 'Sanchita',
 'Sohel',
 'Subhra',
 'Santanu',
 'Anwesha',
 'Archita',
 'Banashree',
 'Rupanjali',
 'Sandipan',
 'Sani',
 'Sayandita',
 'Dipsanu',
 'Puja',
 'Barnali',
 'Bapan',
 'Binoy',
 'Suparna',
 'Samhati',
 'Gitanjali',
 'Prasenjit',
 'Dipika',
 'Ashmita',
 'Ela',
 'Shibasrita',
 'Swagata',
 'Barsita',
 'Nabanita',
 'Pritam',
 'Sourav',
 'Mithun',
 'Jabanika',
 'Neha',
 'Dipayan',
 'Subhradip',
 'Tania',
 'Nisha',
 'Subhankar',
 'Rahul',
 'Mahammed',
 'Pinaki',
 'Soummyamay',
 'Adhitya',
 'Joydeep',
 'Anujit',
 'Swamik',
 'Anurima',
 'Juma',
 'Rakesh',
 'Pritam',
 'Debika',
 'Kaja',
 'Nababrata',
 'Abir',
 'Juwel',
 'Raj',
 'Dipjoy',
 'Dipul',
 'Puja',
 'Gopal',
 'Rupai',
 'Dipankar',
 'Nirma',
 'Rajesh',
 'Susmita',
 'Megha',
 'Chiranjit',
 'Sandipan',
 'Jhuma',
 'Jyanti',
 'Shnigdha',
 'Baishakhi',
 'Joysree',
 'Saheli',
 'Sagar',
 'Sujoy',
 'Gourab',
 'Prasanta',
 'Nabanita',
 'Sushikha',
 'Barnali',
 'Debashree',
 'Susmita',
 'Sanjib',
 'Srijaya',
 'Sarmili',
 'Shilpa',
 'Bishal',
 'Sayan',
 'Suraj',
 'Rupan',
 'Suman',
 'Khakchang',
 'Raktim',
 'Barnita',
 'Vivek',
 'Parmita',
 'Nikita',
 'Sorasikha',
 'Krishna',
 'Debabrata',
 'Debasish',
 'Gourab',
 'Arghadeep',
 'Kunal',
 'Samrat',
 'Raju',
 'Sourav',
 'Nayan',
 'Niday',
 'Suman',
 'Riya',
 'Ganesh',
 'Nitai',
 'Dibakar',
 'Tapas',
 'Sourab',
 'Chiranjit',
 'Shubankar',
 'Sagar',
 'Amit',
 'Nabarun',
 'Kabita',
 'Swarup',
 'Abhishek',
 'Titash',
 'Raju',
 'Dhiman',
 'Akash',
 'Ankit',
 'Laxmi',
 'Dipak',
 'Sayan',
 'Swarup',
 'Dwiptanu',
 'Subham',
 'Sanghamitra',
 'Riya',
 'Kallol',
 'Sreema',
 'Sourav',
 'Ijajul',
 'Sarmistha',
 'Nandita',
 'Meldoi',
 'Bilku',
 'Ajay',
 'Viki',
 'Jogamoy',
 'Soumyadip',
 'Sagar',
 'Shuvadeep',
 'Shibam',
 'Ranjit',
 'Rana',
 'Sujan',
 'Mousumi',
 'Sakina',
 'Sharmistha',
 'Ankita',
 'Aditi',
 'Anita',
 'Shilpi',
 'James',
 'Hrithik',
 'Rohan',
 'Suman',
 'Vivekananda',
 'Niranjan',
 'Priya',
 'Papan',
 'Nayan',
 'Smriti',
 'Mwchang',
 'Nayan',
 'Reshmi',
 'Ajoy',
 'Ankita',
 'Sudipa',
 'Ratan',
 'Popi',
 'Prasanta',
 'Sagarika',
 'Sourav',
 'Rakesh',
 'Sanpad',
 'Priya',
 'Bhanupriya',
 'Abhijit',
 'Prajoy',
 'Rakesh',
 'Nabanita',
 'Ananya',
 'Priyanka',
 'Mousumi',
 'Puja',
 'Sangita',
 'Mousumi',
 'Priyanka',
 'Rajesh',
 'Shuvankar',
 'Ankur',
 'Bijit',
 'Supriya',
 'Ajoy',
 'Ajit',
 'Bimal',
 'Tushar',
 'Baishali',
 'Joysree',
 'Baishali',
 'Rahul',
 'Aparupa',
 'Abhik',
 'Susmita',
 'Ashmita',
 'Nilanjana',
 'Diptanu',
 'Papiya',
 'Aparupa',
 'Priya',
 'Subham',
 'Riki',
 'Aijak',
 'Rajesh',
 'Antarip',
 'Pinki',
 'Ankur',
 'Sourav',
 'Joy',
 'Bijoy',
 'Sankar',
 'Pinku',
 'Binoy',
 'Parthiba',
 'Rima',
 'Amrita',
 'Barsha',
 'Payal',
 'Pritam',
 'Bina',
 'Nandita',
 'Dipan',
 'Debarghya',
 'Anjana',
 'Abhijit',
 'Sangita',
 'Tania',
 'Pahor',
 'Chandan',
 'Shyantan',
 'Amit',
 'Payel',
 'Sujata',
 'Sucharita',
 'Happy',
 'Uday',
 'Akhiya',
 'Bipasha',
 'Viki',
 'Abhishikta',
 'Rohan',
 'Tania',
 'Dipjoy',
 'Lipika',
 'Nabaran',
 'Lipika',
 'Payel',
 'Mampi',
 'Sangita',
 'Mamoni',
 'Bandana',
 'Sutapa',
 'Tanmoy',
 'Shubhadeep',
 'Smriti',
 'Samarjit',
 'Priya',
 'Sonali',
 'Mrinmoy',
 'Bapan',
 'Sujan',
 'Aditi',
 'Himangshu',
 'Suman',
 'Anamika',
 'Taniya',
 'Priya',
 'Jewel',
 'Prahar',
 'Nidhi',
 'Kashmita',
 'Papiya',
 'Kowshik',
 'Debalina',
 'Shyamasree',
 'Sarbani',
 'Ankita',
 'Sagar',
 'Sandeepa',
 'Abhishek',
 'Ankita',
 'Sayani',
 'Rajdip',
 'Binoy',
 'Ankita',
 'Debabrata',
 'Bhgyasree',
 'Sumita',
 'Parimal',
 'Sagar',
 'Tania',
 'Mitan',
 'Jeet',
 'Sujata',
 'Deepjoy',
 'Abhik',
 'Aliza',
 'Akash',
 'Krishan',
 'Surajit',
 'Rajat',
 'Shibani',
 'Pritam',
 'Tanurima',
 'Priyanka',
 'Suradwipa',
 'Subhankar',
 'Rajesh',
 'Sagar',
 'Lima',
 'Amit',
 'Siyari',
 'Sulanki',
 'Chameli',
 'Puja',
 'Ankita',
 'Md',
 'Paramita',
 'Lal',
 'Jaysmita',
 'Jhuma',
 'Janaki',
 'Bindu',
 'Sanjay',
 'Sandipan',
 'Trini',
 'Jhimli',
 'Santu',
 'Shreyasi',
 'Subhankar',
 'Suraj',
 'Abhijit',
 'Panchamita',
 'Sagarika',
 'Anamika',
 'Martina',
 'Kishan',
 'Suparna',
 'Sanchar',
 'Mallika',
 'Ranita',
 'Balai',
 'Tushar',
 'Sourav',
 'Sourav',
 'Ankita',
 'Raju',
 'Rency',
 'Jayanta',
 'Debajit',
 'Rinku',
 'Sagar',
 'Moushumi',
 'Deepshikha',
 'Joye',
 'Tanushree',
 'Surabhi',
 'Thomas',
 'Mukesh',
 'Akash',
 'Aparna',
 'Sarathi',
 'Rabin',
 'Tania',
 'Siddartha',
 'Khumsarik',
 'Tanmay',
 'Sayantan',
 'Priya',
 'Payal',
 'Paheli',
 'Joy',
 'Joydeep',
 'Biswajit',
 'Joy',
 'Tumpa',
 'Ramu',
 'Beauty',
 'Deepjyoti',
 'Papi',
 'Debasree',
 'Prashanta',
 'Shayan',
 'Tayan',
 'Mahamaya',
 'Angkita',
 'Brishti',
 'Rupa',
 'Atish',
 'Subrata',
 'Akankha',
 'Bishal',
 'Rajib',
 'Rupa',
 'Pritam',
 'Mousumi',
 'Suraj',
 'Kubui',
 'Sagarika',
 'Sharmistha',
 'Arpita',
 'Sunam',
 'Sonai',
 'Jackson',
 'Subham',
 'Tirtha',
 'Susmita',
 'Arpita',
 'Baishali',
 'Diptanu',
 'Mousumi',
 'Rita',
 'Puja',
 'Subham',
 'Payel',
 'Tapas',
 'Rahul',
 'Pritam',
 'Payel',
 'Priyanka',
 'Md',
 'Ranjana',
 'Dipanjan',
 'Birulal',
 'Satyajit',
 'Amarjit',
 'Shilpa',
 'Sujata',
 'Manoj',
 'Subhra',
 'Sakshi',
 'Arup',
 'Pampa',
 'Sumiel',
 'Chiranjit',
 'Dipshi',
 'Rupam',
 'Keya',
 'Alpana',
 'Sayantan',
 'Tanushree',
 'Thakurchan',
 'Uddab',
 'Roshni',
 'Surajit',
 'Abul',
 'Reshmi',
 'Aparupa',
 'Aktar',
 'Pratima',
 'Priyanka',
 'Madhumita',
 'Sourav',
 'Priya',
 'Shipra',
 'Sajal',
 'Surajit',
 'Malati',
 'Tanmoy',
 'Sumana',
 'Rakesh',
 'Manika',
 'Khumli',
 'Payel',
 'Dibakar',
 'Anima',
 'Susmita',
 'Anupama',
 'Priyanka',
 'Kishan',
 'Nabamita',
 'Debashish',
 'Gargil',
 'Sambhu',
 'Saikat',
 'Dipak',
 'Sumit',
 'Pulak',
 'Amendra',
 'Biswalal',
 'Nayan',
 'Bakul',
 'Prakash',
 'Poulami',
 'Dipa',
 'Jhuma',
 'Ram',
 'Subhrajit',
 'Susmita',
 'Biswajit',
 'Loisi',
 'Puja',
 'Priya',
 'Sushmita',
 'Sunanda',
 'Abhijit',
 'Pritam',
 'Anup',
 'Dipankar',
 'Panchami',
 'Prasenjit',
 'Arup',
 'Mamata',
 'Abhijit',
 'Bapi',
 'Bipasha',
 'Naithokti',
 'Amlan',
 'Sandhya',
 'Sourav',
 'Sagnik',
 'Biswajit',
 'Swarna',
 'Susmita',
 'Haripada',
 'Payel',
 'Soma',
 'Moutoshi',
 'Priyanka',
 'Md',
 'Dipankar',
 'Jayasree',
 'Neha',
 'Jutan',
 'Shanu',
 'Susmita',
 'Nandita',
 'Krishna',
 'Raju',
 'Jyoti',
 'Aditi',
 'Amjad',
 'Jaspal',
 'Ranisha',
 'Debasish',
 'Ankita',
 'Pragati',
 'Digbijoy',
 'Prakash',
 'Chiranjit',
 'Bishal',
 'Subhradip',
 'Monalisa',
 'Abhijit',
 'Suparna',
 'Sujan',
 'Priyanka',
 'Santana',
 'Ankita',
 'Chayan',
 'Prasanta',
 'Rahul',
 'Susmita',
 'Shaibal',
 'Shayanta',
 'Biswajit',
 'Subhendu',
 'Anamika',
 'Sudip',
 'Debayan',
 ...]

In [29]:
# 2Return the Index label if some condition is satisfied over a column in Pandas Dataframe
indexs=df[df["hs_pass_year"]>2017].index.to_list()
indexs

[0,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 143,
 144,
 145,
 146,
 147,
 148,
 150,
 152,
 153,
 154,
 155,
 156,
 157,
 159,
 160,
 161,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 283,
 284,
 285,
 286,
 287,
 288,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 463,
 464,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 568,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 620,
 621,
 622,
 623,
 624,
 625,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 996,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 ...]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5143 entries, 0 to 5142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   form_no               5143 non-null   int64
 1   name                  5143 non-null   object
 2   category              5143 non-null   object
 3   minority              5143 non-null   object
 4   gender                5143 non-null   object
 5   hs_total              5143 non-null   int64
 6   hs_pass_year          5143 non-null   int64
 7   first_choice_sub      3602 non-null   object
 8   first_choice_marks    5143 non-null   int64
 9   second_choice_sub     3602 non-null   object
 10  second_choice_marks   5143 non-null   int64
 11  first_choice_stream   5143 non-null   object
 12  second_choice_stream  5143 non-null   object
dtypes: int64(5), object(8)
memory usage: 522.5+ KB

In [31]:
# 3 Drop rows from the dataframe based on certain condition applied on a column
# Drop the rows where first_choice_marks=0
df=df.drop(df[df["first_choice_marks"]==0].index,axis=0)
df

,form_no,name,category,minority,gender,hs_total,hs_pass_year,first_choice_sub,first_choice_marks,second_choice_sub,second_choice_marks,first_choice_stream,second_choice_stream
0,1801371,Susmita Bhowmik,UR,NO,F,381,2018,Mathematics,80,Mathematics,80,Physical Science,Physical Science
1,1803096,Ankur Das,SC,NO,M,262,2018,Education,61,Bengali,58,Arts,Arts
2,1801287,Rashmita Tanti,UR,NO,M,278,2018,Human Physiology,74,Botany,74,Bio Science,Bio Science
7,1801105,Snehabrata Dasgupta,UR,NO,M,327,2018,Chemistry,78,Zoology,78,Physical Science,Bio Science
8,1800886,Bijan Sankar Das,SC,NO,M,363,2018,Physics,80,Chemistry,74,Physical Science,Physical Science
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5056,1824153,Mesak Lalmuanfela,ST,NO,M,298,2016,English,74,English,74,Arts,Arts
5057,1824486,Ratul Chakraborty,UR,NO,M,415,2018,Physics,85,Physics,85,Physical Science,Physical Science
5058,1812856,Rahul Paul,UR,NO,M,373,2018,Human Physiology,84,Botany,84,Bio Science,Physical Science
5059,1822484,Sutapa Modak Bhowmik,UR,NO,F,337,2018,Zoology,56,Zoology,56,Bio Science,Bio Science
5142,501,Jayatri Datta,UR,NO,F,368,2018,Sociology,86,Sociology,86,Arts,Arts

Task 5

In [32]:
#How to get list of parameters name from a function in Python
import inspect 
import numpy as np
print(inspect.signature(np.linspace))

# How to Print Multiple Arguments in Python

def func(*args,**kwargs):
    for i in args:
        print(i)
    for j in kwargs:
        print(f"{j}:{kwargs[j]}")
func(2,3,name="nobody",hobby="code")

# Python program to find the power of a number using recursion
def pow(num,power):
    if power==0:
        return 1
    return num*pow(num,power-1)
print(f"5 raised to power 3={pow(5,3)}")

(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
2
3
name:nobody
hobby:code
5 raised to power 3=125